# Generated by Django 6.0.6 on 2026-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
    ]
