# Generated by Django 6.0.6 on 2026-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_schedule',
            field=models.TextField(blank=True),
        ),
    ]
