# Generated by Django 6.0.6 on 2026-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_ai_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_priority',
            field=models.TextField(blank=True),
        ),
    ]
