# Generated by Django 6.0.6 on 2026-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_ai_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_recommendation',
            field=models.TextField(blank=True),
        ),
    ]
