# Generated by Django 6.0.6 on 2026-06-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('streak', models.IntegerField(default=0)),
                ('completed_today', models.BooleanField(default=False)),
            ],
        ),
    ]
